const coffeeData = [
  {
    id: 1,
    name: "Espresso El Balar",
    slug: "espresso-el-balar",
    origin: "Costa Rica",
    recommendedFor: ["Filter Methods"],
    aroma: ["Tropical Fruit", "Green Apple", "Cherry Sugus", "Melon"],
    description:
      "Cultivado en las montañas de San Antonio Huista, Huehuetenango, encontramos el café Primavera, que crece a una altitud de 1,550 a 1,650 metros sobre el nivel del mar. Esta región, famosa por su microclima y su rica biodiversidad, proporciona las condiciones ideales para cultivar cafés de alta calidad que destacan por su sabor.",
    origin: "Guatemala",
    Producer: "G & F Exporters",
    prices: [
      { weight: 250, price: 8.99 },
      { weight: 500, price: 15.99 },
      { weight: 1000, price: 29.99 },
    ],
    imageUrl: "1.png",
    processing: "Natural",
    altitude: "1800 masl",
    cuppingScore: 87,
  },
  {
    id: 2,
    name: "Espresso El Balar",
    origin: "Costa Rica",
    recommendedFor: ["Filter Methods"],
    aroma: ["Tropical Fruit", "Green Apple", "Cherry Sugus", "Melon"],
    description:
      "Cultivado en las montañas de San Antonio Huista, Huehuetenango, encontramos el café Primavera, que crece a una altitud de 1,550 a 1,650 metros sobre el nivel del mar. Esta región, famosa por su microclima y su rica biodiversidad, proporciona las condiciones ideales para cultivar cafés de alta calidad que destacan por su sabor.",
    origin: "Guatemala",
    Producer: "G & F Exporters",
    prices: [
      { weight: 250, price: 8.99 },
      { weight: 500, price: 15.99 },
      { weight: 1000, price: 29.99 },
    ],
    imageUrl: "1.png",
    processing: "Natural",
    altitude: "1800 masl",
    cuppingScore: 87,
  },
  {
    id: 2,
    name: "Espresso El Balar",
    origin: "Costa Rica",
    recommendedFor: ["Filter Methods"],
    aroma: ["Tropical Fruit", "Green Apple", "Cherry Sugus", "Melon"],
    description:
      "Cultivado en las montañas de San Antonio Huista, Huehuetenango, encontramos el café Primavera, que crece a una altitud de 1,550 a 1,650 metros sobre el nivel del mar. Esta región, famosa por su microclima y su rica biodiversidad, proporciona las condiciones ideales para cultivar cafés de alta calidad que destacan por su sabor.",
    origin: "Guatemala",
    Producer: "G & F Exporters",
    prices: [
      { weight: 250, price: 8.99 },
      { weight: 500, price: 15.99 },
      { weight: 1000, price: 29.99 },
    ],
    imageUrl: "1.png",
    processing: "Natural",
    altitude: "1800 masl",
    cuppingScore: 87,
  },
  {
    id: 2,
    name: "Espresso El Balar",
    origin: "Costa Rica",
    recommendedFor: ["Filter Methods"],
    aroma: ["Tropical Fruit", "Green Apple", "Cherry Sugus", "Melon"],
    description:
      "Cultivado en las montañas de San Antonio Huista, Huehuetenango, encontramos el café Primavera, que crece a una altitud de 1,550 a 1,650 metros sobre el nivel del mar. Esta región, famosa por su microclima y su rica biodiversidad, proporciona las condiciones ideales para cultivar cafés de alta calidad que destacan por su sabor.",
    origin: "Guatemala",
    Producer: "G & F Exporters",
    prices: [
      { weight: 250, price: 8.99 },
      { weight: 500, price: 15.99 },
      { weight: 1000, price: 29.99 },
    ],
    imageUrl: "1.png",
    processing: "Natural",
    altitude: "1800 masl",
    cuppingScore: 87,
  },
  {
    id: 2,
    name: "Espresso El Balar",
    origin: "Costa Rica",
    recommendedFor: ["Filter Methods"],
    aroma: ["Tropical Fruit", "Green Apple", "Cherry Sugus", "Melon"],
    description:
      "Cultivado en las montañas de San Antonio Huista, Huehuetenango, encontramos el café Primavera, que crece a una altitud de 1,550 a 1,650 metros sobre el nivel del mar. Esta región, famosa por su microclima y su rica biodiversidad, proporciona las condiciones ideales para cultivar cafés de alta calidad que destacan por su sabor.",
    origin: "Guatemala",
    Producer: "G & F Exporters",
    prices: [
      { weight: 250, price: 8.99 },
      { weight: 500, price: 15.99 },
      { weight: 1000, price: 29.99 },
    ],
    imageUrl: "1.png",
    processing: "Natural",
    altitude: "1800 masl",
    cuppingScore: 87,
  },
  {
    id: 2,
    name: "Espresso El Balar",
    origin: "Costa Rica",
    recommendedFor: ["Filter Methods"],
    aroma: ["Tropical Fruit", "Green Apple", "Cherry Sugus", "Melon"],
    description:
      "Cultivado en las montañas de San Antonio Huista, Huehuetenango, encontramos el café Primavera, que crece a una altitud de 1,550 a 1,650 metros sobre el nivel del mar. Esta región, famosa por su microclima y su rica biodiversidad, proporciona las condiciones ideales para cultivar cafés de alta calidad que destacan por su sabor.",
    origin: "Guatemala",
    Producer: "G & F Exporters",
    prices: [
      { weight: 250, price: 8.99 },
      { weight: 500, price: 15.99 },
      { weight: 1000, price: 29.99 },
    ],
    imageUrl: "1.png",
    processing: "Natural",
    altitude: "1800 masl",
    cuppingScore: 87,
  },
  {
    id: 2,
    name: "Espresso El Balar",
    origin: "Costa Rica",
    recommendedFor: ["Filter Methods"],
    aroma: ["Tropical Fruit", "Green Apple", "Cherry Sugus", "Melon"],
    description:
      "Cultivado en las montañas de San Antonio Huista, Huehuetenango, encontramos el café Primavera, que crece a una altitud de 1,550 a 1,650 metros sobre el nivel del mar. Esta región, famosa por su microclima y su rica biodiversidad, proporciona las condiciones ideales para cultivar cafés de alta calidad que destacan por su sabor.",
    origin: "Guatemala",
    Producer: "G & F Exporters",
    prices: [
      { weight: 250, price: 8.99 },
      { weight: 500, price: 15.99 },
      { weight: 1000, price: 29.99 },
    ],
    imageUrl: "1.png",
    processing: "Natural",
    altitude: "1800 masl",
    cuppingScore: 87,
  },
  {
    id: 2,
    name: "Espresso El Balar",
    origin: "Costa Rica",
    recommendedFor: ["Filter Methods"],
    aroma: ["Tropical Fruit", "Green Apple", "Cherry Sugus", "Melon"],
    description:
      "Cultivado en las montañas de San Antonio Huista, Huehuetenango, encontramos el café Primavera, que crece a una altitud de 1,550 a 1,650 metros sobre el nivel del mar. Esta región, famosa por su microclima y su rica biodiversidad, proporciona las condiciones ideales para cultivar cafés de alta calidad que destacan por su sabor.",
    origin: "Guatemala",
    Producer: "G & F Exporters",
    prices: [
      { weight: 250, price: 8.99 },
      { weight: 500, price: 15.99 },
      { weight: 1000, price: 29.99 },
    ],
    imageUrl: "1.png",
    processing: "Natural",
    altitude: "1800 masl",
    cuppingScore: 87,
  },
];

module.exports = coffeeData;
